import { Language } from './types';

export const STRINGS: Record<string, Record<Language, string>> = {
  appName: { en: 'FasalDrishti', hi: 'फसलदृष्टि' },
  appTagline: { en: 'AI-Powered Crop Insurance: Transparency for Farmers', hi: 'एआई-संचालित फसल बीमा: किसानों के लिए पारदर्शिता' },
  pmfbyDetails: { en: 'PMFBY Details', hi: 'पीएमएफबीवाई विवरण' },
  impactMetrics: { en: 'Impact Metrics', hi: 'प्रभाव मेट्रिक्स' },
  claimsPaid: { en: 'Claims Paid', hi: 'दावों का भुगतान' },
  loginAsFarmer: { en: 'Login as Farmer', hi: 'किसान के रूप में लॉगिन करें' },
  loginAsAuthority: { en: 'Login as Authority', hi: 'अधिकारी के रूप में लॉगिन करें' },
  mobileAadhaar: { en: 'Mobile Number / Aadhaar ID', hi: 'मोबाइल नंबर / आधार आईडी' },
  otpPassword: { en: 'OTP / Password', hi: 'ओटीपी / पासवर्ड' },
  login: { en: 'Login', hi: 'लॉगिन' },
  logout: { en: 'Logout', hi: 'लॉगआउट' },
  farmerDashboard: { en: 'Farmer Dashboard', hi: 'किसान डैशबोर्ड' },
  authorityDashboard: { en: 'Authority Dashboard', hi: 'अधिकारी डैशबोर्ड' },
  myCropStatus: { en: 'My Crop Status', hi: 'मेरी फसल की स्थिति' },
  newImageUpload: { en: 'New Image Upload', hi: 'नई छवि अपलोड करें' },
  claimsHistory: { en: 'Claims History', hi: 'दावों का इतिहास' },
  healthScore: { en: 'Health Score', hi: 'स्वास्थ्य स्कोर' },
  damageType: { en: 'Damage Type', hi: 'क्षति का प्रकार' },
  recommendation: { en: 'Recommendation', hi: 'सिफारिश' },
  listenToAnalysis: { en: 'Listen to Analysis', hi: 'विश्लेषण सुनें' },
  uploadImagePrompt: { en: 'Upload a photo of your crop for AI analysis.', hi: 'एआई विश्लेषण के लिए अपनी फसल की एक तस्वीर अपलोड करें।' },
  selectImage: { en: 'Select Image', hi: 'छवि चुनें' },
  analyzing: { en: 'Analyzing...', hi: 'विश्लेषण हो रहा है...' },
  analysisComplete: { en: 'Analysis Complete', hi: 'विश्लेषण पूरा हुआ' },
  imageUploadGuide: { en: 'Ensure the image captures the entire plant and ground area.', hi: 'सुनिश्चित करें कि छवि में पूरा पौधा और जमीन का क्षेत्र शामिल हो।' },
  imageReceived: { en: 'Image received. Analysis in progress.', hi: 'छवि प्राप्त हुई। विश्लेषण प्रगति पर है।' },
  chatbotPrompt: { en: 'Ask me about your crop or claim status.', hi: 'मुझसे अपनी फसल या दावे की स्थिति के बारे में पूछें।' },
  startConversation: { en: 'Start Conversation', hi: 'बातचीत शुरू करें' },
  stopConversation: { en: 'Stop Conversation', hi: 'बातचीत बंद करें' },
  totalRedAlerts: { en: 'Total Red Alerts', hi: 'कुल रेड अलर्ट' },
  pendingVerifications: { en: 'Pending Verifications', hi: 'लंबित सत्यापन' },
  farmerID: { en: 'Farmer ID', hi: 'किसान आईडी' },
  location: { en: 'Location', hi: 'स्थान' },
  aiAnalysisReport: { en: 'AI Analysis Report', hi: 'एआई विश्लेषण रिपोर्ट' },
  viewRawImage: { en: 'View Raw Geo-tagged Image', hi: 'रॉ जियो-टैग की गई छवि देखें' },
  about: { en: 'About FasalDrishti', hi: 'फसलदृष्टि के बारे में' },
  aboutText: { en: 'This project aims to replace manual bias with AI/ML models deployed in the PMFBY portal for objective loss assessment, bringing transparency and efficiency to crop insurance claims.', hi: 'इस परियोजना का उद्देश्य निष्पक्ष नुकसान मूल्यांकन के लिए पीएमएफबीवाई पोर्टल में तैनात एआई/एमएल मॉडल के साथ मैनुअल पूर्वाग्रह को बदलना है, जिससे फसल बीमा दावों में पारदर्शिता और दक्षता आए।' },
  language: { en: 'Language', hi: 'भाषा' },
  speak: { en: 'Speak', hi: 'बोलें' },
  listening: { en: 'Listening...', hi: 'सुन रहा है...' },
  welcomeFarmer: { en: 'Welcome, Farmer!', hi: 'आपका स्वागत है, किसान!' },
  howItWorks: { en: 'How It Works', hi: 'यह कैसे काम करता है' },
  step1Title: { en: '1. Upload Image', hi: '१. छवि अपलोड करें' },
  step1Desc: { en: 'Capture and upload a geo-tagged image of your crop using your phone.', hi: 'अपने फोन का उपयोग करके अपनी फसल की एक जियो-टैग की गई छवि कैप्चर और अपलोड करें।' },
  step2Title: { en: '2. AI Analysis', hi: '२. एआई विश्लेषण' },
  step2Desc: { en: 'Our advanced AI analyzes the image for health, damage, and stress factors.', hi: 'हमारा उन्नत एआई स्वास्थ्य, क्षति और तनाव कारकों के लिए छवि का विश्लेषण करता है।' },
  step3Title: { en: '3. Get Insights', hi: '३. अंतर्दृष्टि प्राप्त करें' },
  step3Desc: { en: 'Receive instant reports, recommendations, and claim assistance.', hi: 'तत्काल रिपोर्ट, सिफारिशें और दावा सहायता प्राप्त करें।' },
  pinDetails: { en: 'Pin Details', hi: 'पिन विवरण' },
  home: { en: 'Home', hi: 'होम' },
  farmerLogin: { en: 'Farmer Login', hi: 'किसान लॉगिन' },
  authorityLogin: { en: 'Authority Login', hi: 'अधिकारी लॉगिन' },
  aiChatbot: { en: 'AI Chatbot', hi: 'एआई चैटबॉट' },
  regionalClaims: { en: 'Regional Claim Analytics', hi: 'क्षेत्रीय दावा विश्लेषण' },
  settled: { en: 'Settled', hi: 'निपटारा' },
  pending: { en: 'Pending', hi: 'लंबित' },
  cropDamageInsights: { en: 'Crop Damage Insights', hi: 'फसल क्षति अंतर्दृष्टि' },
  crop: { en: 'Crop', hi: 'फसल' },
  incidents: { en: 'Incidents', hi: 'घटनाएं' },
  primaryCause: { en: 'Primary Cause', hi: 'मुख्य कारण' },
  weatherAlerts: { en: 'Live Weather Alerts', hi: 'लाइव मौसम अलर्ट' },
  severeThunderstorm: { en: 'Severe Thunderstorm', hi: 'गंभीर आंधी' },
  heatwave: { en: 'Heatwave', hi: 'लू' },
  floodWarning: { en: 'Flood Warning', hi: 'बाढ़ की चेतावनी' },
};

export const useLocalization = (language: Language) => {
  return (key: keyof typeof STRINGS) => STRINGS[key][language];
};
